<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@taglib uri="http://struts.apache.org/tags-html" prefix="html"%>
<%@taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<html>
<head>
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />

<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Terms and Conditions</title>
</head>
<body bgcolor="silver">
<body>
<html:html>
    
<p>पात्रता asatisamajdarpan.com के एक सदस्य के रूप में रजिस्टर या इस साइट का उपयोग करने के लिए, आप भारत के कानूनों के अनुसार कानूनी विवाह की आयु का होना चाहिए (वर्तमान में, महिलाओं के लिए 18 वर्ष या उससे अधिक है और पुरुषों के लिए 21 वर्ष या अधिक।)</p>
<p>हम asatisamajdarpan.com  इसके द्वारा हमारी साइट में तैनात विज्ञापनों और चित्रों व्यक्तियों द्वारा प्रस्तुत किया गया है कि दावा करते हैं। asatisamajdarpan.com  किसी भी उल्लंघन के लिए जिम्मेदार नहीं ठहराया जा सकता। asatisamajdarpan.com संभव के रूप में सही रूप में इस और अन्य जुड़े दस्तावेजों में जानकारी बनाने का प्रयास किया गया है, यह सूचना के आधार में किसी भी व्यक्ति के मद की सटीकता या मुद्रा के रूप में noguarantee देता है। इस और अन्य संबंधित दस्तावेजों में जानकारी जरूरी asatisamajdarpan.com  के विचार प्रतिबिंबित नहीं करता है और हम उपलब्ध कराई गई जानकारी के लिए कोई जिम्मेदारी का दावा है।</p>
<p>ऑनलाइन सामग्री। राय, सलाह, बयानों, प्रस्तावों, या अन्य जानकारी या सामग्री asatisamajdarpan.com  के अपने संबंधित लेखकों में से उन लोगों और नहीं कर रहे हैं asatisamajdarpan.com  सेवा के माध्यम से उपलब्ध कराया गया है, और जरूरी पर भरोसा नहीं किया जाना चाहिए। ऐसे लेखक ऐसी कथावस्तु के लिए पूरी तरह से ज़िम्मेदार हैं। asatisamajdarpan.com  सेवा पर किसी भी जानकारी की सटीकता, पूर्णता, या उपयोगिता की गारंटी नहीं है और न ही गोद ले और न ही समर्थन किया है और न ही किए गए किसी भी विचार, सलाह, या बयान की सटीकता या विश्वसनीयता के लिए जिम्मेदार है। किसी भी परिस्थिति asatisamajdarpan.com  किसी भी नुकसान या जानकारी या asatisamajdarpan.com  सेवा पर तैनात अन्य सामग्री पर किसी की निर्भरता से उत्पन्न क्षति के लिए जिम्मेदार होगा, या asatisamajdarpan.com को प्रेषित प्रदर्शित करने या किसी भी दूर करने के लिए सभी अधिकार सुरक्षित रखता है विस्तार। </p>
<p>asatisamajdarpan.com के लिए और न ही, उपयोगकर्ता, सदस्यों द्वारा या सेवा में के साथ जुड़े या उपयोग किया उपकरण या प्रोग्रामिंग के किसी भी कारण होता है, चाहे साइट पर या asatisamajdarpan.com  सेवा के संबंध में तैनात किसी भी गलत या गलत सामग्री के लिए ज़िम्मेदार नहीं है किसी भी प्रयोक्ता के संचालन और / या सदस्य asatisamajdarpan.com सेवा की ऑनलाइन या ऑफलाइन या नहीं। </p>
<p>asatisamajdarpan.com ऑपरेशन या प्रसारण, संचार लाइन विफलता, चोरी या विनाश या अनधिकृत उपयोग, या में परिवर्तन, उपयोगकर्ता और / या सदस्य संचार में किसी भी त्रुटि, चूक, रुकावट, हटाने, दोष, देरी के लिए कोई जिम्मेदारी नहीं होगी।</p>
<p>asatisamajdarpan.com किसी भी समस्या या किसी भी टेलीफोन नेटवर्क या लाइनों की तकनीकी खराबी के लिए जिम्मेदार नहीं है, कंप्यूटर ऑन लाइन सिस्टम, सर्वर या प्रदाताओं, कंप्यूटर उपकरण, सॉफ्टवेयर, तकनीकी समस्याओं या यातायात भीड़ के कारण ई-मेल की विफलता या खिलाड़ियों इंटरनेट पर या उपयोगकर्ता और / या सदस्यों के लिए या किसी अन्य व्यक्ति के कंप्यूटर से संबंधित या asatisamajdarpan.com  साइट और / या संबंध में के संबंध में सामग्री भाग लेने या डाउनलोड करने से उत्पन्न करने के लिए चोट या क्षति सहित उसके किसी वेब साइट या संयोजन, पर asatisamajdarpan.com  सेवा के साथ। किसी भी परिस्थिति में asatisamajdarpan.com  साइट या सेवा और / या किसी भी सामग्री asatisamajdarpan.com  साइट पर पोस्ट या asatisamajdarpan.com  सदस्यों को प्रेषित की किसी के उपयोग से उत्पन्न किसी भी नुकसान या क्षति के लिए जिम्मेदार होगा। के माध्यम से या द्वारा वैवाहिक प्रोफ़ाइल (एस) के आदान-प्रदान asatisamajdarpan.com किसी भी तरह से / asatisamajdarpan.com  द्वारा किसी भी वैवाहिक प्रस्ताव और / या सिफारिश के रूप में नहीं लगाया जाना चाहिए। asatisamajdarpan.com  के उपयोग के अनुसार स्थापित, वैवाहिक संबंधों के बाहर उत्पन्न होने वाले किसी भी व्यक्ति को किसी भी नुकसान या क्षति के लिए जिम्मेदार है, या बाद में नहीं होगा। asatisamajdarpan.com  स्पष्ट रूप से एक विशेष उद्देश्य या गैर उल्लंघन के लिए फिटनेस के किसी भी वारंटी को अस्वीकार IS'and के रूप में साइट और सेवा 'प्रदान की जाती हैं। asatisamajdarpan.com  की गारंटी नहीं दे सकता है और साइट और / या asatisamajdarpan.com  सेवा के उपयोग से किसी भी विशिष्ट परिणाम वादा नहीं करता।</p>

<p>asatisamajdarpan.com  सेवा के एक सदस्य बनने करके, आप asatisamajdarpan.com  से कुछ विशिष्ट ई-मेल प्राप्त करने के लिए सहमत हैं। सभी विवादों jabalpur अधिकार क्षेत्र केवल के अधीन किया जाएगा पहुँचने और वेबसाइट को देखने के पूर्वगामी कंटेंट, पढ़ा गया किसी भी आरक्षण बिना नहीं समझा और उन पर सहमत हो गया है कि पुष्टि करता है। आप का उपयोग और आप पूर्वगामी साथ सहमत तभी इस वेबसाइट की सामग्री को देखने चाहिए।</p>

<p>We asatisamajdarpan.com  hereby claim that advertisements and pictures posted in our site have been submitted by individuals. asatisamajdarpan.com  can not be held responsible for any violations. While Asati samaj has attempted to make the information in this and other associated documents as accurate as possible, it gives noguarantee as to the accuracy or currency of any individual item in the information base. The information in this and other associated documents does not necessarily reflect the views of the asatisamajdarpan.com and we claim no Responsibility for any information provided.</p>
<p>ONLINE CONTENT. Opinions, advice, statements, offers, or other information or content made available through the asatisamajdarpan.com service are those of their respective authors and not of asatisamajdarpan.com  and should not necessarily be relied upon. Such authors are solely responsible for such content. asatisamajdarpan.com does not guarantee the accuracy, completeness, or usefulness of any information on the service and neither adopts nor endorses nor is responsible for the accuracy or reliability of any opinion, advice, or statement made. Under no circumstances will asatisamajdarpan.com be responsible for any loss or damage resulting from anyone's reliance on information or other content posted on the asatisamajdarpan.com service, or transmitted to asatisamajdarpan.com reserves all rights to display or remove any detail.</p>
<p>asatisamajdarpan.com is not responsible for any incorrect or inaccurate Content posted on the Site or in connection with the asatisamajdarpan.com Service, whether caused by Users, Members or by any of the equipment or programming associated with or utilized in the Service, nor for the conduct of any User and/or Member of the asatisamajdarpan.com Service whether online or offline.</p>
<p>asatisamajdarpan.com assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, User and/or Member communications.</p>

<p>asatisamajdarpan.com is not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of e-mail or players on account of technical problems or traffic congestion on the Internet or at any web site or combination thereof, including injury or damage to Users and/or Members or to any other person's computer related to or resulting from participating or downloading materials in connection with the asatisamajdarpan.com Site and/or in connection with the asatisamajdarpan.com Service. Under no circumstances will asatisamajdarpan.com be responsible for any loss or damage resulting from anyone's use of the Site or the Service and/or any Content posted on asatisamajdarpan.com Site or transmitted to asatisamajdarpan.com Members. The exchange of matrimonial profile(s) through or by asatisamajdarpan.com should not in any way be construed as any matrimonial offer and/or recommendation from/by asatisamajdarpan.com shall not be responsible for any loss or damage to any individual arising out of, or subsequent to, matrimonial relations established pursuant to the use of asatisamajdarpan.com The Site and the Service are provided 'AS-IS'and 
expressly disclaims any warranty of fitness for a particular purpose or non-infringement. NemaSamaj.com cannot guarantee and does not promise any specific results from use of the Site and/or the asatisamajdarpan.com Service.
By becoming a Member of the asatisamajdarpan.com service, you agree to receive certain specific e-mail from asatisamajdarpan.com All disputes will be subject to Jabalpur jurisdiction only.</p>

<p>ACCESSING AND VIEWING THE WEBSITE CONFIRMS THAT THE FOREGOING CONTENT HAS BEEN READ, UNDERSTOOD AND AGREED UPON WITHOUT ANY RESERVATIONS. YOU SHOULD ACCESS AND VIEW THE CONTENT OF THIS WEBSITE ONLY IF YOU AGREE WITH THE FOREGOING.</p>

</html:html>
</body>
</html>